# C compiler
CC = cc

# Preprocessor flags:
#  - add include path for project headers
#  - generate dependency (.d) files for headers
#  - define SYSCONFDIR macro at compile time
CPPFLAGS = -Isrc/include -MMD -MP -DSYSCONFDIR=\"/etc\"

# Compiler warning flags
CFLAGS = -Wall -Wextra

# Linker flags (library search paths)
LDFLAGS = -Llibs

# Libraries to link against
LDLIBS = -lm

# All C source files in src/
SRC := $(wildcard src/*.c)

# Object files mirrored under build/
# Example: src/main.c -> build/main.o
OBJ := $(SRC:src/%.c=build/%.o)

# Mark targets that do not represent real files
.PHONY: clean build

# Link all object files into the final binary
# Order-only dependency ensures the build directory exists
build/homed: $(OBJ) | build
	$(CC) $(OBJ) $(LDFLAGS) $(LDLIBS) -o $@

# Ensure the build/ directory exists
build:
	mkdir -p build

# Compile each .c file into a corresponding .o file under build/
# Order-only dependency ensures build/ exists before compilation
build/%.o: src/%.c | build
	@mkdir -p $(dir $@)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

# Remove all build artifacts
clean:
	rm -rf build

# Include dependency files generated by the compiler
# The '-' prefix prevents errors if files do not exist yet
-include $(OBJ:.o=.d)
